name: plantdisease_new
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite: any
  image_picker: ^0.8.0+3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  permission_handler: ^8.1.2
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   
   
    
   
    - assets/model_unquant.tflite
    
  
    - assets/labels.txt
    
    
    
    - assets/images/acne.jpeg
    - assets/images/acneorrosacea.jpeg
    - assets/images/Actinic_Keratosis_Basal.jpeg
    - assets/images/Actinic_keratosis.jpeg
    - assets/images/Actinic_Keratosis_Basal.jpeg
    - assets/images/Atopic_Dermatitis.jpeg
    - assets/images/Basal_Cell_Carcinoma.jpeg
    - assets/images/Cellulitis_Impetigo.jpeg
    - assets/images/Dermatofibroma.jpeg
    - assets/images/Eczema.jpeg
    - assets/images/Exanthems_or_Drug.jpeg
    - assets/images/Hair_Loss_.jpeg
    - assets/images/Herpes_HPV.jpeg
    - assets/images/Light_Diseases.jpeg
    - assets/images/Lupus.jpeg
    - assets/images/Melanoma_Skin_Cancer.jpeg
    - assets/images/melanoma.jpeg
    - assets/images/Nail_Fungus.jpeg
    - assets/images/nevus.jpeg
    - assets/images/Pigmented_Benign_.jpeg
    - assets/images/Poison_Lvy.jpeg
    - assets/images/Psoriasis_Lichen.jpeg
    - assets/images/Scabies_Lyme.jpeg
    - assets/images/Seborrheic_Keratoses.jpeg
    - assets/images/Ski_ Allergy.jpeg
    - assets/images/Squamous_Cel.jpeg
    - assets/images/Systemic_Disease.jpeg
    - assets/images/Urticaria_Hives.jpeg
    - assets/images/Vascular_Lesion.jpeg
    - assets/images/Vasculitis.jpeg
    - assets/images/arkaplan.jpg
    - assets/images/atopicdermatitis.jpg
    - assets/images/cellu.jpeg
    - assets/images/bullous.jpeg
    - assets/images/wart.jpeg
    - assets/images/hair.jpeg
    - assets/images/new.jpg
    - assets/images/tina.jpg
    - assets/images/eczama.jpg

    








 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
